language: java
jdk:
  - openjdk11

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew build"

경:
  - mkdir -p before-deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성
  - cp scripts/*.sh before_deploy/
  - cp appspec.yml before_deploy/
  - cp build/libs/*.jar before_deploy/
  - cd before_deploy && zip -r before_deploy * #before_deploy로 이동 후 전체 압축
  - cd ../ && mkdir -p deploy # 상위 디렉토리로 이동 후 deploy 디렉토리 생성
  - mv before_deploy/before_deploy.zip deploy/nemo-fridge.zip # deploy로 zip파일 이동

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: nemofridge-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: deploy # before_deploy에서 생성한 디렉토리

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: nemofridge-build # S3 버킷
    key: nemo-fridge.zip # S3 버킷에 저장된 springboot-webservice.zip 파일을 EC2로 배포
    bundle_type: zip
    application: nemo-fridge # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: nemo-fridge-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2

# 성공 실패 여부 알림
notifications:
  email:
    recipients:
      - chappse6@gmail.com