version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/app/step2/zip/
    overwrite: yes

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
      ruans: ec2-user